
version: '2.4'

services:
    postgres:
        image: postgres:13-alpine
        ports:
            - '5432:5432'
        volumes:
            - 'pg_api_restful_js_node_ts_typeorm:/var/lib/postgresql/data'
        environment: 
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: docker
volumes:
    pg_api_restful_js_node_ts_typeorm:
